### ISSUE TITLE
After putting width why is it becoming so long yet?

### ISSUE THREAD

**Issue by Angryman18** [TanStack/table#4356]
### Describe the bug

i have put the width in that email column but its still going so long.
data is dummy.
![Screenshot from 2022-09-02 17-04-33](https://user-images.githubusercontent.com/63530626/188131222-5f28f9f6-3a2c-42db-b880-dd2b04576fd8.png)

### Your minimal, reproducible example

nope

### Steps to reproduce

simple self explainatory

### Expected behavior

it shouldn't exceed it's width

### Screenshots or Videos

![Screenshot from 2022-09-02 17-04-33](https://user-images.githubusercontent.com/63530626/188131371-85df7c06-2a03-4e07-99b6-9f7522e07640.png)

### Platform

Linux

### react-table version

7.7

### TypeScript version

only JS

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by talatkuyuk** [comment]
I suppose this is a CSS issue. Since the email is so long, the CSS isn't able to truncate it according to the CSS that you defined.

If you add some of CSS rules below, you will see the change:
```css
td {
    white-space: wrap;
    overflow: hidden; 
    text-overflow: ellipsis;
    max-width: <a static value in pixel / character etc>;
}

td:hover {
    overflow: unset;
    text-overflow: unset;
}
```

But keep in your mind, safari and chrome show different behavior according to my experience. You should play with the CSS.
